# Generated by Django 5.1.5 on 2025-01-25 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miga', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='projects_completed',
            new_name='assignments_completed',
        ),
    ]
